In [2]:
import numpy as np 
import pandas as pd

In [5]:
s = pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [11]:
pop = pd.Series([1444,1393,323,278],["India","china","usa","indonesia"],
                 name = "population_millions")

In [12]:
print(pop)

India        1444
china        1393
usa           323
indonesia     278
Name: population_millions, dtype: int64

In [14]:
print(pop[pop > 500])

India    1444
china    1393
Name: population_millions, dtype: int64

In [39]:
q1 = pd.Series({"laptops":12,"Phones":340,"tablets":177})
q2 = pd.Series({"Phones":44,"laptops":474,"watches":73})
print(q1+q2)

Phones     384.0
laptops    486.0
tablets      NaN
watches      NaN
dtype: float64

DATAFRAME

In [21]:
df = pd.DataFrame({
    "name": ["Asha","Bill","Chen","diya","Evan"],
    "dept": ["IT","HR","IT","Finance","HR"],
    "salary": [52000,48000,47999,75000,50000],
    "city": ["Delhi","Mumbai","surat","agra","delhi"]
}
)
print(df)

   name     dept  salary    city
0  Asha       IT   52000   Delhi
1  Bill       HR   48000  Mumbai
2  Chen       IT   47999   surat
3  diya  Finance   75000    agra
4  Evan       HR   50000   delhi

In [25]:
print(df.shape)
print(list(df.columns))
df.info()
df.describe()

(5, 4)
['name', 'dept', 'salary', 'city']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
name      5 non-null object
dept      5 non-null object
salary    5 non-null int64
city      5 non-null object
dtypes: int64(1), object(3)
memory usage: 140.0+ bytes

             salary
count      5.000000
mean   54599.800000
std    11524.031421
min    47999.000000
25%    48000.000000
50%    50000.000000
75%    52000.000000
max    75000.000000

In [30]:
raw = pd.DataFrame({
    "order_id":["1001","1002","1003"],
    "amount":["2500","1880","3200"]
})
print(raw.dtypes)

order_id    object
amount      object
dtype: object

In [32]:
print(raw["amount"].sum())

250018803200

In [34]:
clean = raw.copy()

In [35]:
clean["order_id"] = pd.to_numeric(clean["order_id"])
clean["amount"] = pd.to_numeric(clean["amount"])

In [44]:
print(clean["amount"].sum())

7580

In [45]:
df

   name     dept  salary    city
0  Asha       IT   52000   Delhi
1  Bill       HR   48000  Mumbai
2  Chen       IT   47999   surat
3  diya  Finance   75000    agra
4  Evan       HR   50000   delhi

In [58]:
people = df.set_index("name")
people

         dept  salary    city
name
Asha       IT   52000   Delhi
Bill       HR   48000  Mumbai
Chen       IT   47999   surat
diya  Finance   75000    agra
Evan       HR   50000   delhi

In [60]:
people.loc["Asha"]

dept         IT
salary    52000
city      Delhi
Name: Asha, dtype: object

In [57]:
people.loc[["Asha","Chen"]]

     dept  salary   city
name
Asha   IT   52000  Delhi
Chen   IT   47999  surat

In [61]:
people.iloc[1]

dept          HR
salary     48000
city      Mumbai
Name: Bill, dtype: object

In [65]:
people.iloc[0:3,0:2]

     dept  salary
name
Asha   IT   52000
Bill   HR   48000
Chen   IT   47999

In [72]:
people[people["salary"] < 49000]

     dept  salary    city
name
Bill   HR   48000  Mumbai
Chen   IT   47999   surat

In [87]:
print(people[(people["dept"] == "IT") & (people["salary"] < 49000)])

     dept  salary   city
name
Chen   IT   47999  surat

In [90]:
people.query('dept == "IT" and salary < 49000')

     dept  salary   city
name
Chen   IT   47999  surat

MISSING DATA

In [94]:
messy = pd.DataFrame({
    "product" : ["Pen","book","bag","lamp","mug"],
    "price" : [20, np.nan, 850, 1200, np.nan],
    "rating" : [4.1, 4.5, np.nan, 4.5, 3.9]
})
messy

  product   price  rating
0     Pen    20.0     4.1
1    book     NaN     4.5
2     bag   850.0     NaN
3    lamp  1200.0     4.5
4     mug     NaN     3.9

In [95]:
messy.isna().sum()

product    0
price      2
rating     1
dtype: int64

In [96]:
filled = messy.copy()

In [97]:
filled["price"] = filled["price"].fillna(filled["price"].mean())

In [99]:
filled["rating"] = filled["rating"].fillna(filled["rating"].median())

In [100]:
print(filled)

  product   price  rating
0     Pen    20.0    4.10
1    book   690.0    4.50
2     bag   850.0    4.25
3    lamp  1200.0    4.50
4     mug   690.0    3.90